import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Tesla Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="ml-2 mr-2 border-spacing-2 p-2 text-3xl font-bold underline bg-blend-color">
          Hello World!
        </h1>
        <button className="bg-sky-700 px-4 py-2 text-black hover:bg-sky-800 sm:px-8 sm:py-3">
          ...
        </button>
      </main>
      <footer></footer>
    </>
  );
}
