import Head from "next/head";
import Navbar from "../components/Navbar";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Tesla Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.cdnfonts.com/css/gotham" rel="stylesheet" />
      </Head>
      <Navbar />
      <main>
        <section className="relative h-screen w-screen flex-col justify-between bg-[url('../assets/ModelY.png')] bg-cover bg-center pt-px">
          <div className="mx-auto pt-[calc(15vh_+_20px)] text-center font-['Gotham']">
            <h1 className="text-[36px] font-medium text-[#171A20] sm:text-[40px]">
              Model Y
            </h1>
            <p className="text-[14px] text-[#171A20] transition delay-300 ease-linear">
              <Link
                href="/drive"
                // ! Does not transition the bottom border to 2px from 1px on hover like it should look back into this.
                className="border-b border-[#171A20] pb-px hover:border-b-[2px]"
              >
                Schedule a Demo Drive
              </Link>
            </p>
          </div>
          <div className="absolute left-0 right-0 bottom-[calc(9vh_+_24px)] mx-auto w-[90%] text-center sm:flex sm:w-[552px] sm:justify-between">
            <button className="rounded bg-[#3D3F42]/[.9] py-2 px-6 text-white drop-shadow max-sm:mx-auto max-sm:block max-sm:w-[95%] sm:w-[264px]">
              <span className="font-['Gotham'] text-[14px]">Custom Order</span>
            </button>
            <button className="block rounded bg-[#E8E7E4]/[.9] py-2 px-6 drop-shadow max-sm:mx-auto max-sm:mt-4 max-sm:w-[95%] sm:w-[264px]">
              <span className="font-['Gotham'] text-[14px] text-[#3D3F42]">
                View Inventory
              </span>
            </button>
          </div>
        </section>
      </main>
      <footer></footer>
    </>
  );
}
